# Simple docker-composer.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /home/cloud/uptime-kuma/data:/app/data
    ports:
      - 127.0.0.1:3001:3001
      - 10.13.13.1:3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
