version: '2'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "1001"
    volumes:
      - /config/grafana/config:/var/lib/grafana
    restart:
      always
