---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-service--immich
  namespace: flux-system
spec:
  dependsOn:
    - name: media-service--immich--config
  path: ./kubernetes/apps/tools/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: yomi-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-service--immich--config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/tools/immich/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: yomi-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
