version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 127.0.0.1:53:53/tcp
      - 127.0.0.1:53:53/udp
      - 10.13.13.1:53:53/tcp
      - 10.13.13.1:53:53/udp
      #- 784:784/udp
      #- 853:853/tcp
      - 127.0.0.1:3005:3000/tcp
      - 127.0.0.1:8085:80/tcp
      #- 443:443/tcp
    volumes:
      - ./data:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    restart: unless-stopped
