# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  port: 8081
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: ""  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
general:
  debug: false                          #Debug mode only for development
  instance_name: "Yomi Search"          #Displayed name
  contact_url: false                    # mailto:contact@example.com
  enable_metrics: true                  #record stats
search:
  safe_search: 1
  autocomplete: "duckduckgo"
